### PR TITLE
Cache

### PR DESCRIPTION
**Pull request by Ttech**
You don't' have to pull everything in but this is an example of how I'd do the Cache plugin, its a mess. and not to mention probably there will be some errors. There's come comments hopefully this helps.

### CODE REVIEW

**Comment by avdg** [comment]
I really like to see the storage outside the cache plugin itself. One way to do that is to implement hooks.

Though this will also cause some refactoring in the db plugin, since I really don't like the fact that db is a plugin (though this is not related to the hooks, they are a result of the refactoring).

**Comment by Ttech** [comment]
I have been saying that for the past few days that we need to take the backends / storage / hooks into a central database - while we COULD make it a library however lets work with the plugin version first.

**Comment by Ttech** [comment]
I've made a simple cache system for now, however, I'm going to have a go at the Database abstraction library/plugin this weekend.

**Comment by avdg** [comment]
I have currently no reasons to merge it now, closing it

**Pull request closed without merging**
