### PR TITLE
Adding more plugin goodness, this should be the final version of the logg

### PR DESCRIPTION
**Pull request by Ttech**
happy now? :P

### CODE REVIEW

**Comment by avdg** [comment]
I keep this ticket open till I figured out whats exactly in this topic branch

**Comment by Ttech** [comment]
What are the issues with this merge? heh

**Comment by avdg** [comment]
I will take a look at this issue after the db gets a stable api. There is no point in adding backends before that is done.

**Comment by avdg** [comment]
Closing this one, since I don't think I will merge this one

**Pull request closed without merging**
